### ISSUE TITLE
Missed pagination when search by keyword

### ISSUE THREAD

**Issue by SiavaRu** [satanasov/phpbbgallery#101]
no pagination code from template..

**Comment by satanasov** [comment]
Hmmm but it doesn't work

I will have to redo it,

**Comment by SiavaRu** [comment]
/gallery/search?keywords=pic
/gallery/search/2?keywords=pic
/gallery/search/3?keywords=pic
it works, but no pagination at the page.

**Comment by satanasov** [comment]
Yeah ... this needs redoing.
