### ISSUE TITLE
Error when edit personal subalbums info

### ISSUE THREAD

**Issue by SiavaRu** [satanasov/phpbbgallery#102]
After submit form on page: /ucp.php?i=-phpbbgallery-core-ucp-main_module&mode=manage_albums&action=edit&album_id=2808

[phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbgallery/core/ucp/main_module.php on line 517: Undefined variable: phpbb_ext_gallery
[phpBB Debug] PHP Notice: in file [ROOT]/ext/phpbbgallery/core/ucp/main_module.php on line 517: Trying to get property of non-object

in server error log
2016/05/17 17:07:42 [error] 9175#9175: *5285941 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function acl_check() on null in /.../ext/phpbbgallery/core/ucp/main_module.php on line 517" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: siava.ru, request: "POST /.../ucp.php?i=-phpbbgallery-core-ucp-main_module&mode=manage_albums&action=edit&album_id=2808 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "siava.ru", referrer: "...deleted../ucp.php?i=-phpbbgallery-core-ucp-main_module&mode=manage_albums&action=edit&album_id=2808"

**Comment by satanasov** [comment]
Fixed by #107
