### ISSUE TITLE
Watermark not displayed

### ISSUE THREAD

**Issue by SiavaRu** [satanasov/phpbbgallery#109]
Path to image is correct. I use default png ext/phpbbgallery/core/images/watermark.png
Permissions set to display watermark.
No errors in log.

**Comment by SiavaRu** [comment]
I think problem in core/controller/file.php
public function display()

when I reverted this function to old watermark displays.

old function contained $this->tool->send_image_to_browser();
send_image_to_browser() was in core/file/file.php

**Comment by satanasov** [comment]
OK. So it's basically fixed.

Issue is deleting the watermarked images. I need to trigger cache purge on changing watermark. This will take some time (probably before tonight I will push the fix)
