### ISSUE TITLE
Saving image gets the image name and no extension

### ISSUE THREAD

**Issue by satanasov** [satanasov/phpbbgallery#112]
When you try to save image you get image name and no extension.

**Comment by Leinad4Mind** [comment]
This problem still exists in last version on chrome.

**Comment by Leinad4Mind** [comment]
I've solved by adding:

`elseif(!$this->tool->image_type)
			{
				$this->tool->image_type = substr($this->tool->image_content_type, 6);
			}`

right after:
`if (!$this->tool->image_content_type)
			{
				trigger_error('NO_MIMETYPE_MATCHED');
			}`

It's not the best approach, but it solves the problem. 
With chrome the $this->tool->image_type was always empty and therefor no extension.
