### ISSUE TITLE
creating user-gallery ends up in \user\user\user\ 

### ISSUE THREAD

**Issue by PhinPhin** [satanasov/phpbbgallery#123]
I tried to create the user-gallery for my (admin-)account. Though nothing happend. Had to click 3 times until the site reloaded and I ended up with \user\user\user\ inside of the gallery... shouldn't be that way, right? :)

Btw. any way to mass-unlock uploaded photos? I can't seem to find a way. If not, feature-request? :)

**Comment by satanasov** [comment]
No this should not be so ... I will take care of it as soon as I have some time (which I don't have lately).

About the feature request - please create new issue with full description.

**Comment by dachris1** [comment]
thats because of the cache, see
https://github.com/satanasov/phpbbgallery/issues/151
