### ISSUE TITLE
destroy user table cache on personal album create/delete

### ISSUE THREAD

**Issue by dachris1** [satanasov/phpbbgallery#151]
in core/user.php "function load_data" you cache the query for 30 seconds,
so you have to delete the cache on personal album creation and deletion in UCP, because if not, no album is displayed after creation and on deletion you get the NO_ALBUM_STEALING error.

my changes:
core/ucp/main_module.php  -> function initialise_album()
ADD
global $users_table;

ADD AFTER
$cache->destroy('sql', $albums_table);
$cache->destroy('sql', $users_table);

same in "function delete_album()"

**Comment by satanasov** [comment]
This is fixed in the Stable Realease
