### ISSUE TITLE
Fatal error: Call to a member function load_users() on null in

### ISSUE THREAD

**Issue by AlexL777** [satanasov/phpbbgallery#152]
Hello developer,

I have unfortunately a problem with this extension with PHPBB 3.2 RC 2. 

When I upload an image and created an image description and then go further, this error is displayed to me.

`Fatal error: Call to a member function load_users() on null in /xxxxxxxxxx/cms/phpbb32/ext/phpbbgallery/core/notification/events/phpbbgallery_new_image.php on line 93`

Where does it come from and how can I fix it?

I use PHP 7.0 and everything else normal.

Thanks in advance.

**Comment by sentralgit** [comment]
I faced this issue, too but with php 5.6 - just FYI

**Comment by satanasov** [comment]
Closing as #160 is the same issue ...
