### ISSUE TITLE
template fixes for 1.2.1

### ISSUE THREAD

**Issue by zenpig** [satanasov/phpbbgallery#153]
Seems like you're already aware of the template issues to be fixed and some like in ucp_gallery.html were pretty easy for me to figure out but core/styles/prosilver/template/gallery/posting_body.html is one that I can't figure out.  Feeling stupid with the css for the likes of "simulate-dt" and all...might hit me but any pointers?

btw, nice work and appreciate all your hard work on continuing this extension.  Functionally, 1.2.1 appears to be working in phpbb3.2.

**Comment by satanasov** [comment]
I will be going after the bugs one by one.

If you have fixed some of the issues I'll be glad to merge your PR.
