### ISSUE TITLE
impossible to connect with phpbb gallery enable

### ISSUE THREAD

**Issue by pokyto** [satanasov/phpbbgallery#160]
hello satanasov

With phpbb Gallery enabled on my 3.2.0 phpbb i can't log in the forum , 

I found this error on my server logs

mydomain.com: [Mon May 22 22:35:57.467263 2017] [proxy_fcgi:error] [pid 28547] [client XXX.XXX.XXX.XXX:56006] AH01071: Got error 'PHP message: PHP Fatal error:  Call to a member function load_users() on null in /home/hosted/usersSpace/17/ftp/mydomain.com/www/ext/phpbbgallery/core/notification/events/phpbbgallery_new_comment.php on line 111\n', referer: http://www.mydomain.com/ucp.php?mode=login

I did not have this error with my 3.1.10 phpbb before the update to 3.2.0 and i must disable the gallery in Phpmyadmin otherwise i can't use the site

any idea ???

Regards

**Comment by Galixte** [comment]
Hi @satanasov,

could you take a lokk, please ?

**Comment by Galixte** [comment]
any news ?

**Comment by pokyto** [comment]
Nope ... i have no skills to deal with that ... I just had to disable the gallery ... i can use the forum but sadely without the gallery

**Comment by Galixte** [comment]
On Apache 2.4 and PHPH 5.6.30 i don’t have this problem, we can presume it’s du to the PHP version used.

**Comment by pokyto** [comment]
here is my PHP Version 5.6.30-0+deb8u1

And this bug only affects some forum members, including me (sic)

**Comment by mldenison** [comment]
I just built a new forum using 3.2.  It was built from the ground up, not upgrading from 3.1.  The original forum (ca 2012) was destroyed by Synology after an automatic phpbb and database update a few days after I had finished it.  I hadn't backed it up.

In any case, once the 3.2 version was done, I installed Gallery and it mostly worked.  However, I could add sub-folders in the back end and they would not show up in the front end.  And vice versa.  I had to disable it.  Darn shame.  I really liked it.

**Comment by Galixte** [comment]
Hi @mldenison, please open a new issue, each issue has his particularities. ;)

**Comment by satanasov** [comment]
OK ... this issue is going under "can't reproduce", but I will make the notification system comaptible with 3.2

**Comment by satanasov** [comment]
This is done in a4af06492fc176fd968b06f60d755cd684da7d05

**Comment by Galixte** [comment]
The commit indicated it’s incorrect. ;)
