### ISSUE TITLE
Last changes on 1.2.1 version (phpBB 3.2.x)

### ISSUE THREAD

**Issue by Galixte** [satanasov/phpbbgallery#161]
Hi @satanasov,

is it normal that the 1.2.0.10 version has more ```(int)``` in ```./phpbbgallery/core/album/manage.php``` file ? 

Especially preceding the ```$this->user_id``` code. See lines 512, 520, 532, 540, 561, 572, 702, 729, 735 & 1038.

Compare with phpBB.com 1.2.0.10 version with MASTER version (1.2.1) because curently on GitHub 1.2.0.10 seems not to be up to date: https://www.phpbb.com/customise/db/extension/phpbb_gallery/support/topic/179671?p=574076#p574076.

**Comment by satanasov** [comment]
1.2.1 branch is not the current branch ... master is current branch.

**Comment by Galixte** [comment]
I talked about MASTER branch it’s indicated in my previous message.

**Comment by satanasov** [comment]
https://github.com/satanasov/phpbbgallery/blob/master/core/album/manage.php#L1025-L1038

You mean this segment?

I'm reviewing the specific code and thinking of changing it ...

**Comment by Galixte** [comment]
I talk about all the next lines: “512, 520, 532, 540, 561, 572, 702, 729, 735 & 1038.”. You can compare easily with Winmerge.

**Comment by satanasov** [comment]
Well darn ... Why the hell this was left out ... I will fox it tonight.

**Comment by Galixte** [comment]
Thanks!
