### ISSUE TITLE
Adding child personal albums broken - for me

### ISSUE THREAD

**Issue by mldenison** [satanasov/phpbbgallery#163]
First, I'm glad Gallery is back for 3.2.

The only problem I've experienced is that if I create child albums under my main album in ACP, they don't show up on the board.  Just the main album.  And if I create them on the main board, they don't show up in ACP.  Just the main album.

Some sort of rights issue I haven't set or set properly?

**Comment by mldenison** [comment]
No, I did not.  I'll do that today and report back.

**Comment by mldenison** [comment]
Hi,

I have not uploaded any photos.  I had to disable the Gallery on my site because it resulted in a confusing issue for people trying to register on my site.  The verbiage for choosing a password is being changed when Gallery is enabled.  The minimum and maximum password values are missing.

**Comment by Galixte** [comment]
@mldenison Could you share some screeshots, please? It could be usefull to find the problem.

**Comment by mldenison** [comment]
Sorry - that would have been useful.  Attached.
![gallery-disabled-passwords](https://user-images.githubusercontent.com/29863803/28470695-8fc19f46-6e08-11e7-81db-201507945a7b.JPG)
![gallery-enabled-passwords](https://user-images.githubusercontent.com/29863803/28470694-8fbe8c8e-6e08-11e7-8a23-03008dbae78b.JPG)

**Comment by Galixte** [comment]
@satanasov some language keys interfere with the original language keys from phpBB.

**Comment by satanasov** [comment]
Probably ... taking a look.

**Comment by satanasov** [comment]
Should be fixed - please check

**Comment by mldenison** [comment]
It is fixed.  I appreciate it.  I will get back to checking the child folders over the next few days.

**Comment by Galixte** [comment]
@mldenison you can open a new topic here: https://www.phpbb.com/customise/db/extension/phpbb_gallery/support. Expose you permission problems, and share some screenshot if needed. ;)

**Comment by satanasov** [comment]
I will have to create some video how-tos ...

@mldenison what kind of permissions you face issues with?
