### ISSUE TITLE
Difference on gallery home between version for phpBB3.0 and phpBB3.2

### ISSUE THREAD

**Issue by satanasdiabolo** [satanasov/phpbbgallery#165]
I'm working of the migration of one of my forum on phpBB3.0 to phpBB3.2.
We are using phpbbgallery on this server, and I notice a big difference on the home between the previous version and the new one
![galery_3 0](https://user-images.githubusercontent.com/1850524/28520012-2c93f0aa-706e-11e7-98b8-fad480f61c8d.PNG)
Version phpBB3.0
![galery_3 2](https://user-images.githubusercontent.com/1850524/28520013-2cac3d90-706e-11e7-8fb3-eb49edb3705d.PNG)
Version phpBB3.2

What settings should I have to retrieve the look & feel of the previous version ?

**Comment by Galixte** [comment]
Hi,

currently, there is no setting for generic albums, only one option for personal albums like your screenshot.

@satanasov, could make in sort to add an option the other albums than personal?

**Comment by satanasov** [comment]
Sorry but I don't get what other albums do yo mean @Galixte. There is an option to show personal albus in front page, and you have the admin defined albums on front page.

@satanasdiabolo you will need to redo the template file for index and create a custom style.

**Comment by Galixte** [comment]
@satanasov there are two kind of albums personal and “generic”.

Personal albums are created by users and “generic” albums are create by admin in ACP.

**Comment by satanasov** [comment]
But the generic albums are displayed by default.

**Comment by Galixte** [comment]
I don’t talk about which album are displayed by default but the style of displaying for the generic albums. 

Currently, generic albums are displayed in white background, the option could display them like forums, like the option for personal albums allows it.

**Comment by satanasov** [comment]
This can be done in styles. No need to create additional complexity.

**Comment by satanasov** [comment]
In $phpbb_root_path/ext/phpbbgallery/core/styles/prosilver/template/gallery/index_body.html

on line 162 replace 



with

**Comment by Galixte** [comment]
Nice! Thanks you @satanasov 👍
