### ISSUE TITLE
Translations missing variables

### ISSUE THREAD

**Issue by jwittorf** [satanasov/phpbbgallery#166]
I'm running phpBB 3.2.0 and the 1.2.1 branch.

On several occasions I'm missing variables in translation strings. For example when I try to upload an avatar that's too big, I just get ` The submitted avatar is pixels wide and pixels high. Avatars must be at least pixels wide and pixels high, but no larger than pixels wide and pixels high.`

This also happens for usernames and password that are too short.

When I disable the extension, everything works as expected.

Is there already a fix?

**Comment by satanasov** [comment]
I think I fixed this few days ago. Please update to current and confirm that issue still exists.

**Comment by jwittorf** [comment]
I merged the master branch into my feature-branch (just added the FLATBOOTS theme and adjusted some templates, no big core/"real programming" changes, just html so that shouldn't be the issue) but it's still as before.

Could you maybe point out the commit fixing this?

**Comment by satanasov** [comment]
OK ... so this thing ... there are some duplicating strings ... I will try to hunt them down ... but please continue reporting them.

**Comment by satanasov** [comment]
This exact issue is fixed. Please report all other you find.
