### ISSUE TITLE
winch is for phpbb  3.2.0

### ISSUE THREAD

**Issue by raykai** [satanasov/phpbbgallery#173]
Hi,

in the phpbb forum, you had a post about the 1.2.1 branch for phpbb v3.2.0 [https://www.phpbb.com/customise/db/extension/phpbb_gallery/support/topic/169206?start=15](https://www.phpbb.com/customise/db/extension/phpbb_gallery/support/topic/169206?start=15) 
but i can't seem to find it here.

Is the master the one we need for phpbb 3.2.0 ? 

thx for your hard work.

**Comment by Galixte** [comment]
Yes MASTER branch is dedicated to 3.2.x version from phpBB: https://www.phpbb.com/customise/db/extension/phpbb_gallery/support/topic/179741. ;)
