### ISSUE TITLE
Major ACP Error when enabling

### ISSUE THREAD

**Issue by WebmasterChuck** [satanasov/phpbbgallery#187]
Hey all:

Just tried installing and activating this Extension and I got the below error in bright red on the top of ACP. I have tried all 3 versions available for download from GH.

Here's my server config:

Database server: MySQL(i) 5.6.36-cll-lve
PHP version: 5.6.32
Board version: 3.2.2

`phpBB encountered an error building the container due to an installed extension. For this reason, all extensions have been temporarily disabled. Please try purging your forum cache. All extensions will automatically be re-enabled once the container error is resolved. If this error continues, please visit phpBB.com for support.`

`Exception: The service "phpbbgallery.acpcleanup.cleanup" has a dependency on a non-existent service "phpbbgallery.core.file.tool".`

`#0 /home/cwaters/public_html/forumtest/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
#1 /home/cwaters/public_html/forumtest/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition(Object(Symfony\Component\DependencyInjection\Definition))
#2 /home/cwaters/public_html/forumtest/vendor/symfony/dependency-injection/Compiler/Compiler.php(104): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /home/cwaters/public_html/forumtest/vendor/symfony/dependency-injection/ContainerBuilder.php(598): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /home/cwaters/public_html/forumtest/phpbb/di/container_builder.php(191): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#5 /home/cwaters/public_html/forumtest/common.php(115): phpbb\di\container_builder->get_container()
#6 /home/cwaters/public_html/forumtest/adm/index.php(23): require('/home/cwaters/p...')
#7 {main}`

**Comment by satanasov** [comment]
You are trying to activate add-on before the core.
