### ISSUE TITLE
Main page menu - 2 Gallery links

### ISSUE THREAD

**Issue by mldenison** [satanasov/phpbbgallery#188]
After installing 3.2.2.1 - and in previous versions - I have 2 Gallery links displayed in the top menu on the main page.  One has a folder image next to it and the other does not.  How can I remove the one without the image.  They both open up to the same page.

![gallery](https://user-images.githubusercontent.com/29863803/35287307-0e9362aa-0030-11e8-8a7e-5436a8185f2c.JPG)

**Comment by satanasov** [comment]
I will take a look. First time this type of issue.

**Comment by satanasov** [comment]
Could not duplicate.
