### ISSUE TITLE
Incompatible with URL Rewriting Enabled

### ISSUE THREAD

**Issue by TarantinoMariachi** [satanasov/phpbbgallery#190]
If we enable URL Rewriting at ACP - Server Settings, the gallery will stop working, and errors will be shown:

`Fatal error: Uncaught Error: Class 'phpbb_gallery' not found in /forum/gallery/album.php:20 Stack trace: #0 {main} thrown in /forum/gallery/album.php on line 20`

**Comment by satanasov** [comment]
This is remnant from old gallery. Probably not full migration from old 1.1.x 

You should never see album.php

**Comment by TarantinoMariachi** [comment]
Ok I'll test again. But I pretty sure I tested on a fresh install.
