### ISSUE TITLE
Bug on Pagination on Search Results

### ISSUE THREAD

**Issue by TarantinoMariachi** [satanasov/phpbbgallery#191]
On search results page, the pagination appears, but if we click to go to page 2, it goes, BUT then if we click again to go to page 3, it keeps on page 2. And page 1 stays always as the active page. The only way to go to page 3 is by clicking on number 3, but then, we can't go back to page 1, since the page 1 button stays always as active.

**Comment by satanasov** [comment]
Could not duplicate!

**Comment by TarantinoMariachi** [comment]
I'll make a video then lol
