### ISSUE TITLE
No Moderation Button!

### ISSUE THREAD

**Issue by TarantinoMariachi** [satanasov/phpbbgallery#194]
We don't have any moderation button so we can access to this page: /gallery/moderate/album/1

And I've tried to add a button with U_MCP, but it redirects to the phpbb moderation page instead of gallery moderation.

**Comment by TarantinoMariachi** [comment]
I've fixed the U_MCP by changing to U_MCP_GALLERY:

https://github.com/satanasov/phpbbgallery/blob/ad820a244bd02c4a928bdd2ac3d24a12d982c8d0/core/controller/album.php#L166


And for adding the moderation option I've added after this line
https://github.com/satanasov/phpbbgallery/blob/ad820a244bd02c4a928bdd2ac3d24a12d982c8d0/core/styles/prosilver/template/gallery/album_body.html#L14

This:
`<!-- IF not S_IN_GALLERY_POPUP and U_MCP --><li><a href="{U_MCP_GALLERY}">{L_MCP}</a></li><!-- ENDIF -->`

Maybe this info can help.

**Comment by satanasov** [comment]
This is not a bug. Route is added to U_MCP and the gallery uses the global MCP link in the menu. I should remove the [Moderator control panel] remnants ...

**Comment by TarantinoMariachi** [comment]
Alright. The problem here was that we don't have anymore any way to go to the gallery moderation page.
