### ISSUE TITLE
Pagination in Search Doesn't Work

### ISSUE THREAD

**Issue by Leinad4Mind** [satanasov/phpbbgallery#221]
If I made a Search and there is many pages of results, and I go to another page, let say the 2nd one,  I am redirected to this url: /gallery/search/2?keywords=&username=&terms=all&sc=1&sf=all&st=0&sk=t&sd=d

But what shows is the search page and not the the 2nd page of results :(

**Comment by satanasov** [comment]
Search is implemented as basic as possible. Accepting request. It will be for the 3.2.2 milestone.

**Comment by Leinad4Mind** [comment]
Solved here: https://github.com/satanasov/phpbbgallery/pull/253
