### ISSUE TITLE
Sql-error

### ISSUE THREAD

**Issue by 69bruno** [satanasov/phpbbgallery#248]
Hi, 
i'm using phpbb3.3.2, installed phpgallery 3.2.2. But i can't upload pictures. I get this Message:
--------------------------------------------------------------------------
Allgemeiner Fehler

SQL ERROR [ mysqli ]

Unknown column 'image_exif_data' in 'field list' [1054]

SQL

INSERT INTO phpbb_gallery_images (image_name, image_name_clean, image_filename, filesize_upload, image_time, image_user_id, image_user_colour, image_username, image_username_clean, image_user_ip, image_album_id, image_status, image_contest, image_allow_comments, image_desc, image_desc_uid, image_desc_bitfield, image_exif_data, image_has_exif) VALUES ('Screenshot_20170326-182410', 'screenshot_20170326-182410', 'd25a1332f87ee42ce56f8f52d9ebdf56.jpg', 51080, 1605194751, '48', 'AA0000', '69Bruno', '69bruno', '2.203.174.132', 1, 3, 0, 1, '', '', '', '', 0)

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 1023
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 195
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 345
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/phpbbgallery/core/upload.php
LINE: 499
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/phpbbgallery/core/upload.php
LINE: 437
CALL: phpbbgallery\core\upload->file_to_database()

FILE: [ROOT]/ext/phpbbgallery/core/upload.php
LINE: 150
CALL: phpbbgallery\core\upload->prepare_file()

FILE: [ROOT]/ext/phpbbgallery/core/controller/upload.php
LINE: 371
CALL: phpbbgallery\core\upload->upload_file()

FILE: [ROOT]/vendor/symfony/http-kernel/HttpKernel.php
LINE: 151
CALL: phpbbgallery\core\controller\upload->main()

FILE: [ROOT]/vendor/symfony/http-kernel/HttpKernel.php
LINE: 68
CALL: Symfony\Component\HttpKernel\HttpKernel->handleRaw()

FILE: [ROOT]/app.php
LINE: 35
CALL: Symfony\Component\HttpKernel\HttpKernel->handle()
---------------------------------------------------------------------
What can i do ?

**Comment by satanasov** [comment]
Please activate EXIF addon

**Comment by 69bruno** [comment]
exif addon was activated

**Comment by satanasov** [comment]
Did it fix it?

**Comment by 69bruno** [comment]
no. in which table has the field to be ?

**Comment by satanasov** [comment]
phpbb_gallery_images

**Comment by 69bruno** [comment]
field not there, fields below only:

"image_id","image_filename","image_name","image_name_clean","image_desc","image_desc_uid","image_desc_bitfield","image_user_id","image_username","image_username_clean","image_user_colour","image_user_ip","image_time","image_album_id","image_view_count","image_status","image_contest","image_contest_end","image_contest_rank","image_filemissing","image_rates","image_rate_points","image_rate_avg","image_comments","image_last_comment","image_allow_comments","image_favorited","image_reported","filesize_upload","filesize_medium","filesize_cache"

**Comment by 69bruno** [comment]
Alter i added this fields by myself

image_has_exif
image_exif_data
and
user_viewexif

i could load up a picture. but the picture is shown as broken

**Comment by 69bruno** [comment]
Sorry, picture isnt broken. only the Image previews

**Comment by satanasov** [comment]
Hmmm this seems like a rewrite issue ...

**Comment by 69bruno** [comment]
The function "imagecreatefromjpeg" is undefined. I don't know, how it must be defined.

[Thu Nov 12 18:47:20.654263 2020] [php7:error] [pid 17223] [client 2.203.174.132:46302] PHP Fatal error:  Uncaught Error: Call to undefined function phpbbgallery\\core\\file\\imagecreatefromjpeg() in /var/www/html/phpBB3/ext/phpbbgallery/core/file/file.php:155\nStack trace:\n#0 /var/www/html/phpBB3/ext/phpbbgallery/core/controller/file.php(421): phpbbgallery\\core\\file\\file->read_image(true)\n#1 /var/www/html/phpBB3/ext/phpbbgallery/core/controller/file.php(208): phpbbgallery\\core\\controller\\file->resize('2', '240', '160', 'filesize_cache')\n#2 /var/www/html/phpBB3/vendor/symfony/http-kernel/HttpKernel.php(151): phpbbgallery\\core\\controller\\file->mini('2')\n#3 /var/www/html/phpBB3/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(phpbb\\symfony_request), 1)\n#4 /var/www/html/phpBB3/app.php(35): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(phpbb\\symfony_request))\n#5 {main}\n  thrown in /var/www/html/phpBB3/ext/phpbbgallery/core/file/file.php on line 155, referer: https://cruiser-lounge.de/app.php/gallery

**Comment by satanasov** [comment]
I will need more info here - php version, server version. Do you have GD installed?

**Comment by 69bruno** [comment]
Forum: cruiser-lounge.de
PHPBB-Version: 3.3.2
Debian-Linux 10
PHP-Version: 7.3.14
Apache-Sever-Version: 2.4.38
MySQL-Version 10.3.22

don't know,what GD means

**Comment by 69bruno** [comment]
I looked up, libgd3 is running on my server. I can't install GD at restart apache doesn't find gd.so. The file is missing in the directory.

**Comment by 69bruno** [comment]
the issue with gd is solved. After several tries the Installation sucseeded. With big Images i get a php_size_overrun. is there another php modul needed ?

**Comment by satanasov** [comment]
No. This is PHP Memory limit size it's on php.ini 

memory_limit = 128M is the option I use ... I don't remember the maximum size it will work with ...

**Comment by 69bruno** [comment]
checked php.ini. 128m was set. changed it to -1, didn't fix it

**Comment by satanasov** [comment]
Hmmm...

Don't change it to -1 ... 

There is size limit that can be opened by GD ... just can't remember how big ... Try doubling it ...

**Comment by 69bruno** [comment]
Set it up To 256M, issue still remains

**Comment by SiavaRu** [comment]
69bruno, RTFM!

**Comment by 69bruno** [comment]
Oh, i did. I didn't find the information, that i need gd-modul. There's also not written, why the php-memory-limit of 128M doesn' t fit for the gallery. In threads i can add any picture, it will be resized wthout an error. The error occurs only in the gallery. because of that i asked here. If tfm gives me solutions, i will read it again.

**Comment by 69bruno** [comment]
With
memory-limit 256M and upload_max_filesize 8M it works well.
Why the columns weren't inserted i couldn't recreate. On another Board they were inserted without issues.
