### ISSUE TITLE
Gallery-Protokoll

### ISSUE THREAD

**Issue by chris1278** [satanasov/phpbbgallery#263]
Hello my friend. I now have your gallery active with version 3.3.0. Runs so far without problems with php 7.4.

I've increased it to php 8 as a test. here, too, it seems to be working at first glance. The only thing I noticed is when you click on Gallery/Gallery log or Gallery log under Extensions in the admin area. Hang it up and nothing loads. You should probably test that.

**Comment by satanasov** [comment]
Could not duplicate.
