### ISSUE TITLE
markup in index_body_block_stats_append.html

### ISSUE THREAD

**Issue by ForumImages** [satanasov/phpbbgallery#35]
ext/phpbbgallery/core/styles/prosilver/template/event/index_body_block_stats_append.html
two open bold tags
<b>{PHPBBGALLERY_INDEX_STATS}<b>
Change to 
<b>{PHPBBGALLERY_INDEX_STATS}</b>

**Comment by satanasov** [comment]
New issue opened with better for understaniding description - #42

Closing this one
