### ISSUE TITLE
Screen size set in config.php was not checked

### ISSUE THREAD

**Issue by huytrang90** [satanasov/phpbbgallery#47]
Since I can't figure out how to use the UI to update my max image size for gallery, (Please let me know), i had to modified the config.php, then go on to the database to update it.  (i already ahve the gallery and don't want to lose data.)

After I change the max image size, I uploaded a photo with 2048xxxx about 1.2M.  It passed the image size, but did not check for the resolution.

Does this mean the setting for size of image being ignored as expected?

Thanks.

**Comment by satanasov** [comment]
There is autoresize option in ACP -> Gallery config. If the size is larger then limit, images are resized.
