### ISSUE TITLE
Error When Adding Configure Gallery Module

### ISSUE THREAD

**Issue by elawrenc** [satanasov/phpbbgallery#51]
This is coming from a database that had the old gallery installed. Everything seems to work except for Configure ACP Gallery Module.  The modules are not added by default and when they are added manually, the following error occurs when trying to access the Configure Gallery Module.

General Error
No mode specified.

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/ext/phpbbgallery/core/acp/config_module.php
LINE: 27
CALL: trigger_error()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: phpbbgallery\core\acp\config_module->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()

**Comment by satanasov** [comment]
Not cleaned update.
