### ISSUE TITLE
Contest albums ?

### ISSUE THREAD

**Issue by zouloufr** [satanasov/phpbbgallery#58]
Hello,
First of all thanks for your hard work, I wanted to ask you where I could create contest albums I can't find it.
Or if you have an ETA of when it'll be available.
Thanks in advance,

**Comment by satanasov** [comment]
Sorry but no ETA. I have a lot other stuff to do now but I will get back to gallery as soon as possible.

**Comment by K07H** [comment]
:+1: :+1: This feature would be awesome!

**Comment by satanasov** [comment]
This now works.
