### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by Galixte** [satanasov/phpbbgallery#59]
Hi @satanasov,

could you take a look about those fixes ? https://www.phpbb.com/community/viewtopic.php?p=14249416#p14249416

**Comment by satanasov** [comment]
I will take a look tomorrow.

**Comment by Galixte** [comment]
It’s done ? https://github.com/satanasov/phpbbgallery/commit/342232b22cfb545f71687d1ab778fee40f0af105
