### ISSUE TITLE
Gallery link in short profile is not showing

### ISSUE THREAD

**Issue by here-we-go** [satanasov/phpbbgallery#61]
Gallery link in short profile is not showing

**Comment by satanasov** [comment]
Hello, 

Showing gallery link at all is a bit a hacked up thing. This will be fixed in the next version.

**Comment by K07H** [comment]
I may have fixed it (just waiting for satanasov to check my last pull request).

**Comment by satanasov** [comment]
I will get to it after 26th... You cold add extra test cases...

**Comment by K07H** [comment]
If you are thinking about Travis, I have no experience with it unfortunately..
Or maybe you are saying I have not tested all possible cases concerning the generation of contact fields? If yes, maybe you could tell me to which scenarios you are thinking so I could check them too?

**Comment by satanasov** [comment]
I was talking about travis.

I will take a look at your code and if it does what it is supposed -> I will write some more test cases (with explanatory documentation, so you can see how it is done if you are interested).

 Lets continue this in #66 discussion.
