### ISSUE TITLE
JavaScript Exception

### ISSUE THREAD

**Issue by Ru13en** [satanasov/phpbbgallery#91]
I've been testing this mod with phpbb 3.1.8.
However, i found some issues with javascript exception.;

Uncaught ReferenceError: dE is not defined

Each time that the mod calls any file that contains a call of that function the above exception is throw. 
I've searched in the prosilver style in core and found the above html files that call that function:

prosilver\template\gallery\recent_body.html
prosilver\template\gallery\posting_body.html
prosilver\template\gallery\imageblock_body.html

Have you forgot some js file?

Thanks

**Comment by satanasov** [comment]
Hello ...

Nope - the file was never included. Just forgot to clean the styles. I'll do it now.

**Comment by Ru13en** [comment]
Thank you  +1:

**Comment by satanasov** [comment]
Hmmm I will wait with cleaning it up ... it appears dE function have some usage ... I will have to find out what.

**Comment by Ru13en** [comment]
Yeah... that's why i asked by any js file that has that function... XD

**Comment by satanasov** [comment]
It's remnant from the old project, but my frontend skills are ... let's say minimum. I will debug what this do and rebuild it, but probably not for 1.2.0

**Comment by Ru13en** [comment]
humm... okay. Maybe i will also try to find out what it is... If i found, i will post it here.

**Comment by satanasov** [comment]
Superb! Knowing what it does will make it easy.

**Comment by Ru13en** [comment]
I found form where that function is and what it does...
In phpbb 3.0, when you go to upload a file, you can add several files in one unique submit.
As you can see in this print:
http://i.imgur.com/EGjCxLX.png

The function is a native function of the style that is not included in the phpbb 3.1.

/**
* Set display of page element
* s[-1,0,1] = hide,toggle display,show
* type = string: inline, block, inline-block or other CSS "display" type
*/
function dE(n, s, type)
{
	if (!type)
	{
		type = 'block';
	}

	var e = document.getElementById(n);
	if (!s)
	{
		s = (e.style.display == '' || e.style.display == type) ? -1 : 1;
	}
	e.style.display = (s == 1) ? type : 'none';
}

Its present in prosilver/template/forum_fn.js file.

**Comment by satanasov** [comment]
I will remove this function from the code. It's irrelevant now.

**Comment by satanasov** [comment]
Closed with a942200c71402b60f61de68d4a5041cb9be57cf8

**Comment by Leinad4Mind** [comment]
The javascript function dE() was replaced with phpbb.toggleDisplay() in phpBB 3.1.0-b3.
