### ISSUE TITLE
Missing template variable in php for style

### ISSUE THREAD

**Issue by Ru13en** [satanasov/phpbbgallery#92]
Hi again,

I saw that you only ported the style front-end from 3.0 and made some hammer like fixes. XD.
However, due the hole refactoring in back-end files, you have removed/lost some template variables.

Example: 
In the phpbb 3.0 code, the file gallery/posting.php had the following code:

		if (!$submit || (isset($process) && !$process->uploaded_files))
		{
			for ($i = 0; $i < $upload_files_limit; $i++)
			{
				$template->assign_block_vars('upload_image', array());
			}
		}

This code allow the template to add several dl tags by requesting the "{upload_image.S_ROW_COUNT}" variable. 

I don't found out where you assign the upload_image template variable in php files...
(I'm trying to do an organization and refactoring of prosilver gallery core style to be more easy to understand and to fix all issues that you have missed).

**Comment by satanasov** [comment]
This is not relevant now. 

We only have 1 upload field allowing selection of multiple files. 

Thanks for the effort. As I said in the other issue - my front end skills are not up to the task. If you could point out all issues I will be more then happy to fix them.
